# This is a basic workflow file to get you started with Actions
name: First Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push events to the main branch
  push:
    branches:
      - main
  # Triggers the workflow on pull request events to the main branch
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # The steps that will be executed by the job
    steps:
      - uses: actions/checkout@v4

      # Run a one-line script   
      - name: Run a one-line script
        run: echo "Hello, world!"

      # Run a multi-line script
      - name: Run a multi-line script
        run: |
          echo "Multi line test 1"
          echo "Multi line test 2"
          echo "Multi line test 3"
